assert (eq (gt 5.0 3.0) true)
assert (eq (lt 1.0 2.0) true)
assert (eq (gt 1.0 5.0) false)
assert (eq (gte 3.0 3.0) true)
assert (eq (lte 2.0 3.0) true)
assert (eq (not false) true)
assert (eq (not true) false)
assert (eq (and true true) true)
assert (eq (and true false) false)
assert (eq (or false true) true)
assert (eq (or false false) false)
~inRange lo,hi,x (and (gte x lo) (lte x hi))
assert (eq (inRange 1.0 10.0 5.0) true)
assert (eq (inRange 1.0 10.0 11.0) false)
