assert (eq (length "hello") 5.0)
assert (eq (length (concat "hello" " world")) 11.0)
assert (eq (uppercase "hello") "HELLO")
assert (eq (lowercase "WORLD") "world")
assert (eq (trim "  hi  ") "hi")
assert (eq (contains "hello world" "world") 1.0)
assert (eq (contains "hello world" "xyz") 0.0)
assert (eq (startsWith "hello" "he") 1.0)
assert (eq (startsWith "hello" "lo") 0.0)
assert (eq (endsWith "hello" "lo") 1.0)
assert (eq (endsWith "hello" "he") 0.0)
assert (eq (replace "hello" "l" "r") "herro")
assert (eq (toFloat "3.14") 3.14)
assert (eq (toString 42.0) "42")
assert (eq (substring "hello world" 0.0 5.0) "hello")
assert (eq (substring "hello world" 6.0 5.0) "world")
