(library
 (name churing_lib)
 (modules parser eval ast types infer codegen)
 (foreign_stubs (language c) (names codegen_stubs))
 (libraries unix llvm llvm.executionengine llvm.all_backends)
 (wrapped false)
 (flags (:standard -w -27)))

(executable
 (name churing)
 (modules churing)
 (libraries churing_lib)
 (flags (:standard -w -27)))
